# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:latest
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data: